### ISSUE TITLE
failed to build libdtrace-rs

### ISSUE THREAD

**Issue by mrdorababu** [SubconsciousCompute/libdtrace-rs#7]
We are facing the following issue while building libdtrace-rs 

```
Compiling libdtrace-rs v0.1.0 (E:\workspace\subcom\testProjects\libdtrace-rs)
error: failed to run custom build command for `libdtrace-rs v0.1.0 (E:\workspace\subcom\testProjects\libdtrace-rs)`

Caused by:
  process didn't exit successfully: `E:\workspace\subcom\testProjects\libdtrace-rs\target\debug\build\libdtrace-rs-5fa49cb4b5c0845a\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rustc-link-lib=dtrace
  cargo:rustc-link-search=native=E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\build\x64\Release\lib\

  --- stderr
  thread 'main' panicked at build.rs:29:6:
  Failed to copy dll: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS E:\workspace\subcom\testProjects\libdtrace-rs>
```

**Comment by cyberphantom52** [comment]
This means dtrace for windows failed to build. Did you setup MS Build tools properly?

**Comment by mrdorababu** [comment]
Build tools are installed while we install the Rust. Do we need to install any additional packages?

**Comment by cyberphantom52** [comment]
> Build tools are installed while we install the Rust. Do we need to install any additional packages?

As per README, we need to choose "Desktop development with C++" while installing and then manually add `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin` to  `PATH`.

Saw your reply on notion, seems like you've skipped these steps.

**Comment by mrdorababu** [comment]
Check the following Output

```
PS E:\workspace\subcom\testProjects\libdtrace-rs> msbuild --version
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.11.2.50704
PS E:\workspace\subcom\testProjects\libdtrace-rs> cargo build
   Compiling libdtrace-rs v0.1.0 (E:\workspace\subcom\testProjects\libdtrace-rs)
error: failed to run custom build command for `libdtrace-rs v0.1.0 (E:\workspace\subcom\testProjects\libdtrace-rs)`

Caused by:
  process didn't exit successfully: `E:\workspace\subcom\testProjects\libdtrace-rs\target\debug\build\libdtrace-rs-5fa49cb4b5c0845a\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rustc-link-lib=dtrace
  cargo:rustc-link-search=native=E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\build\x64\Release\lib\

  --- stderr
  thread 'main' panicked at build.rs:29:6:
  Failed to copy dll: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS E:\workspace\subcom\testProjects\libdtrace-rs>
```

**Comment by mrdorababu** [comment]
```

PS E:\workspace\subcom\testProjects\libdtrace-rs> .\build-dtrace.ps1
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 1/22/2024 12:11:43 PM.
Project "E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\opendtrace.sln" on n
ode 1 (dtrace_dll:Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\opendtrace.sln" (1)
is building "E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\lib\lib.vcxproj"
 (2) on node 1 (Rebuild target(s)).
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\
Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v143 (Platform Tool
set = 'v143') cannot be found. To build using the v143 build tools, please install v143 b
uild tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecti
ng the Project menu or right-click the solution, and then selecting "Retarget solution".
[E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\lib\lib.vcxproj]
Done Building Project "E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\lib\li
b.vcxproj" (Rebuild target(s)) -- FAILED.

Done Building Project "E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\opendt
race.sln" (dtrace_dll:Rebuild target(s)) -- FAILED.


Build FAILED.

"E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\opendtrace.sln" (dtrace_dll:
Rebuild target) (1) ->
"E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\lib\lib.vcxproj" (Rebuild ta
rget) (2) ->
(PrepareForBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v16
0\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v143 (Platform To
olset = 'v143') cannot be found. To build using the v143 build tools, please install v143
 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selec
ting the Project menu or right-click the solution, and then selecting "Retarget solution"
. [E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace\lib\lib.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.77
PS E:\workspace\subcom\testProjects\libdtrace-rs\target\dtrace>

```

**Comment by cyberphantom52** [comment]
Dora had set the `LIBCLANG_PATH` for some embedded development. Fixed after we set it to the new clang installation.
